# Generated by Django 6.0.5 on 2026-06-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vertrag',
            old_name='buchumsdatum',
            new_name='buchungsdatum',
        ),
    ]
